Update publishing workflow
Signed-off-by: Roger Barker <roger.barker@swirldslabs.com>

diff --git a/.github/workflows/zxf-publish-release.yaml b/.github/workflows/zxf-publish-release.yaml
--- a/.github/workflows/zxf-publish-release.yaml
+++ b/.github/workflows/zxf-publish-release.yaml
@@ -48,6 +48,47 @@ jobs:
           fetch-depth: 0
           submodules: recursive
 
+      - name: Install Semantic Version Tools
+        run: |
+            echo "::group::Download Semver Binary"
+            sudo curl -L -o /usr/local/bin/semver https://raw.githubusercontent.com/fsaintjacques/semver-tool/master/src/master
+            echo "::endgroup::"
+            echo "::group::Change SemVer Binary Permissions"
+            sudo chmod +x /usr/local/bin/semver
+            echo "::endgroup::"
+            echo "::group::Show SemVer Binary Version Info"
+            semver --version
+            echo "::endgroup::"
+            
+      - name: Set up Rust
+        uses: dtolnay/rust-toolchain@b3b07ba8b418998c39fb20f53e8b695cdcc8de1b # v1
+        with:
+          toolchain: 1.88.0
+          components: rustfmt, toml-cli, cargo-info
+    
+      - name: Extract Cargo.toml Versions
+        id: cargo-versions
+        run: |
+          SDK_PACKAGE_VERSION="$(toml get Cargo.toml package.version --raw)"
+          SDK_PROTO_VERSION="$(toml get protobufs/Cargo.toml package.version --raw)"
+          SDK_TCK_VERSION="$(toml get tck/Cargo.toml package.version --raw)"
+          
+          echo "sdk-version=${SDK_PACKAGE_VERSION}" >>"${GITHUB_OUTPUT}"
+          echo "sdk-proto-version=${SDK_PROTO_VERSION}" >>"${GITHUB_OUTPUT}"
+          echo "sdk-tck-version=${SDK_TCK_VERSION}" >>"${GITHUB_OUTPUT}"
+      
+      - name: Proto Subpackage Publish Required
+        id: proto-required
+        run: |
+          PUBLISH_REQUIRED="false"
+          CRATES=("hedera-proto" "hiero-sdk-proto")
+          for CRATE in "${CRATES[@]}"; do
+            if ! curl -sSLf "https://crates.io/api/v1/crates/${CRATE}/${{ steps.cargo-versions.outputs.sdk-proto-version }}" >/dev/null 2>&1;
+                PUBLISH_REQUIRED="true"
+            fi
+          done
+          echo "proto-publish-required=${PUBLISH_REQUIRED}" >>"${GITHUB_OUTPUT}"
+
       - name: Extract SDK Tag Information
         id: tag
         run: |
@@ -81,7 +122,7 @@ jobs:
           echo "type=${PREREL_TYPE}" >>"${GITHUB_OUTPUT}"
 
   publish:
-    name: Publish to crates.io
+    name: Publish SDK to crates.io
     needs:
       - validate-release
     runs-on: hiero-client-sdk-linux-medium
@@ -98,11 +139,14 @@ jobs:
           submodules: recursive
 
       - name: Set up Rust
-        uses: actions/setup-rust@v1
+        uses: dtolnay/rust-toolchain@b3b07ba8b418998c39fb20f53e8b695cdcc8de1b # v1
         with:
-          rust-version: stable
+          toolchain: 1.88.0
+          components: rustfmt, toml-cli
 
       - name: Publish to crates.io
         env:
-          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
-        run: cargo publish --locked
+          CARGO_HG_TOKEN: ${{ secrets.CRATES_HG_TOKEN }}
+        run: |
+          export CARGO_REGISTRY_TOKEN="${CARGO_HG_TOKEN}"
+          cargo publish --locked
